
  
name: Rails Unit Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db:
        image: mariadb:10.2
        volumes:
         - /srv/docker/sockets/mariadb:/var/run/mysqld
        env:         
          MARIADB_USER: root
          MARIADB_ROOT_PASSWORD: 123456                    
          
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby 3.0.2
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.2
      - name: Build and test with Rake
        env:
          RAILS_ENV: test           
        run: |        
          gem install bundler          
          bundle install --jobs 4 --retry 3
          bundle exec rails db:create
          bundle exec rails db:migrate
          bundle exec rake
      - name: Rubocop Check
        run: |
          bundle exec rubocop
